### PR TITLE
CSwordBibleModuleInfo: Support for av11n (fixed Bible bounds)

### PR DESCRIPTION
**Pull request by kalemas**
Bounds did not work for av11n Bibles

### CODE REVIEW

**Comment by jaakristioja** [comment]
To be honest, I don't understand what the exact issue is or how the fix works. Could you please explain in more detail (and also add the description to the commit message)?

**Comment by kalemas** [comment]
Oh, it may be hard to restore in memory. But there was issue with OT only Bibles displayed empty verses for whole NT and vice versa. It may be fixed yet, i should check.

**Comment by jaakristioja** [comment]
I apologize for the long delay.

**Comment by kalemas** [comment]
@jaakristioja confirm that issue still persists in v3.0.2
image
 
The PR will fix Bible boundaries but missed books will still produce such results.

I have to update PR, but not sure for testing, building on windows is still a trial((

**Comment by kalemas** [comment]
i remember that there was approach with Scope attribute in module's conf file, or `VerseKey::setSkipConsecutiveLinks(true)` may handle this case better...

**Comment by kalemas** [comment]
unfortunately i can not confirm that fix works, book selector still display correct books in both cases (probably because i test non av11n Biles), text view still display empty verses for whole missed testament. I have to get of how text rendering changed last years.

**Comment by kalemas** [comment]
close in favor of #359

**Pull request closed without merging**
