### PR TITLE
New French translation

### PR DESCRIPTION
**Pull request by LAfricain**
Please see also question on issue #133

### CODE REVIEW

**Comment by gholmlund** [comment]
This is for BibleTime Mobile only.

**Comment by LAfricain** [comment]
> This is for BibleTime Mobile only.

Why?

**Comment by gholmlund** [comment]
| Why?
My mistake. I missed seeing the bibletime_ui_fr.ts file. I am working on a BibleTime Mobile release with this change. The desktop translations are normally processed when a new release is made. I see you updated Transifex which is the normal way translations are updated. Are both Transifex changes and this pull request equivalent? If yes, this pull request is not needed.

**Comment by LAfricain** [comment]
> Are both Transifex changes and this pull request equivalent? If yes, this pull request is not needed.

Yes, but I did the pull request to go faster :)

> The desktop translations are normally processed when a new release is made.

When the next? Could it be in Ubuntu 18.04 LTS?

**Comment by gholmlund** [comment]
| When the next? Could it be in Ubuntu 18.04 LTS?

1. We are currently not planning a release soon. We wait for more changes than we currently have. The project manager makes this decision.
2. We don't package for ubuntu so I can't say when it will get into ubuntu.
3. Ubuntu 18.04 has hit feature freeze and would not accept this change.

Are you able to compile BibleTime? If yes, I would suggest compiling the stable-2.11 branch with your translation file changes.

**Pull request closed without merging**
