### PR TITLE
Infodisplay

### PR DESCRIPTION
**Pull request by kalemas**
Draft header. If there is no objections i'll proceed.

### CODE REVIEW

**Comment by jaakristioja** [comment]
In c0da994 ("added type for...") you only added the typedef, but you didn't replace any instances of `QList<const CSwordModuleInfo*>` with `CSwordModuleInfoList` elsewhere in code. I suggest you do that in c0da994 otherwise we just have one type alias which is used in some places but not in others.

I haven't yet read through 94a8bc9 ("header for new..."), but I think you shouldn't just add code which is not being used. Please also remove all the legacy `CInfoDisplay::decode*` code in the same commit, making sure it doesn't break anything.

PS: `git add -p ...`, `git rebase -i ...` and `git push --force` might be help you accomplish this.

**Comment by kalemas** [comment]
1. Good point
2. It will be complete replacement in one commit, at moment I just declare what I m going to do.

**Comment by kalemas** [comment]
1 - complete, comments?

**Comment by jaakristioja** [comment]
See the comments I just added to the commit. It generally looks good, but it should be broken up into multiple commits, because there are multiple different changes/fixes, and not all of them are directly related to the typedef being added. If you keep one change/fix per commit, I have no problem with you committing directly to the master branch.... we can always fix each other's messes later :smile:

**Comment by jaakristioja** [comment]
Please review the comments I added to the commits. Otherwise these look much better than the previous **HUGE** commit you wanted me to review and merge. These are much easier to review (one logical change per commit). If you had split up the changes before I would probably not have misunderstood that `unindexedModules()`-related `const` change. When reviewing long difficult to comprehend commits such things are too easy to miss.

**Comment by kalemas** [comment]
I do not know to preserve translations after this transition.

also i forget to implement module look up  in decodeCrossReference(), it done later

**Comment by kalemas** [comment]
sorry, does code i motioned above ever executed? 

``` c++
-    // const bool isBible = true;
-    const CSwordModuleInfo * module = btConfig().getDefaultSwordModuleByType("standardBible");
-    if (!module)
-        module = m_mainWindow->getCurrentModule();
```

in cinfodisplay.cpp ?

Because in Mini i can do anything at all if there is no "standardBible"

**Comment by kalemas** [comment]
By the way, i would like to merge and maintain qmake build scripts for bibletime in master. Have you objections?

It will simplify for me work over BibleTime patches as i will not be engaged with merging recent version in working tree each time. Translation would also be much easier as one could clone my new   repo with submodules and just hit Run in QtCreator.

**Comment by kalemas** [comment]
We do not have to do anything with translation becasue after updating, existing  strings will be used. Translator would only update status for strings with changed context.

Issue with m_mainWindow->getCurrentModule was fixed and i had decided not to merge qmake scripts but keep them on the top of my own clone.

Closing.

**Pull request closed without merging**
