### PR TITLE
New entries for the missing languages.

### PR DESCRIPTION
**Pull request by LAfricain**
In this pull request I added all the mission entries in the module managere for the missing languages displayed with the iso code. The iso codes are now replaced by the real names.
(und not used).
I used extra scripts in the file for the original language. I hope it was not wrong. Please check it. If needed I can change it.

### CODE REVIEW

**Comment by jaakristioja** [comment]
Unfortunately this will have to wait for BibleTime 3.1, because we are in a string freeze for 3.0.

**Comment by LAfricain** [comment]
OK, even if it's better to have the name in English rather the iso code ;)

**Comment by jaakristioja** [comment]
I had to completely refactor the `CLanguageMgr` implementation in the master branch, so this pull request will have to be refactored as well. My apologies about that. Please feel free to open a new pull request and close this one, if this makes things easier for you.

Note also that you do not need to provide translations of the language names in C++ code, only the English (US) names of the respective languages. I hope my recent changes to the C++ code also make it a bit more clear to the reader.

**Comment by jaakristioja** [comment]
Closing in favor of PR #345

**Pull request closed without merging**
